### ISSUE TITLE
BuildProject ：CMakeset_target_properties Can not find target to add properties to: IrrXML

### ISSUE THREAD

**Issue by jaggerjiang** [vilbeyli/VQE#133] opened 2021-03-26 15:35 UTC
CMake Error at CMakeLists.txt:193 (set_target_properties):
  set_target_properties Can not find target to add properties to: IrrXML

CMake Error at CMakeLists.txt:194 (set_target_properties):
  set_target_properties Can not find target to add properties to: uninstall

**Comment by vilbeyli** [comment] 2021-03-29 17:22
Are submodules synced?

`git submodule update --init --recursive`

Assuming you've solved it, closing the issue. 
Please feel free to reopen if the issue is not fixed.

**Closed by vilbeyli** 2021-03-29 17:22 UTC
